/**
 * This copy of Woodstox XML processor is licensed under the
 * Apache (Software) License, version 2.0 ("the License").
 * See the License for details about distribution rights, and the
 * specific rights regarding derivate works.
 *
 * You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/
 *
 * A copy is also included in the downloadable source code package
 * containing Woodstox, in file "ASL2.0", under the same directory
 * as this file.
 */
package com.acessoatodos.places;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Getter;
import lombok.Setter;

import java.util.HashSet;
import java.util.Set;

/**
 * Created by NoteSamsung on 30/08/2016.
 */
@Getter
@Setter
@DynamoDBTable(tableName = PlaceDynamoModel.TABLE_NAME_ACCESIBILITIES_OF_PLACES)
public class PlaceDynamoModel {

    public static final String TABLE_NAME_ACCESIBILITIES_OF_PLACES = "acessibilitiesOfPlaces";

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName="id")
    private String id;

    @DynamoDBAttribute(attributeName="acessibilities")
    private Set<Integer> acessibilities;

    @DynamoDBRangeKey(attributeName="placeId")
    private String placeId;
}
