package com.acessoatodos.places;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Getter;
import lombok.Setter;

import java.util.Set;

/**
 * Created by NoteSamsung on 30/08/2016.
 */
@Getter
@Setter
@DynamoDBTable(tableName = PlaceDynamoModel.TABLE_NAME_ACCESIBILITIES_OF_PLACES)
public class PlaceDynamoModel {

    public static final String TABLE_NAME_ACCESIBILITIES_OF_PLACES = "acessibilitiesOfPlaces";

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName="id")
    private String id;

    @DynamoDBAttribute(attributeName="acessibilities")
    private Set<Integer> acessibilities;

    @DynamoDBRangeKey(attributeName="placeId")
    private String placeId;
}
