package com.acessoatodos.places;

import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@DynamoDBTable(tableName = "places")
class PlacesTableModel {
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey
	String id;

	@DynamoDBRangeKey
	String placeId;

	@DynamoDBAttribute
	Set<Integer> acessibilities;
}
